host = "0.0.0.0"
port = 8080
path = "data"
writer_memory = 200000000
log_level = "debug"
json_parsing_threads = 1
bulk_buffer_size = 10000
auto_commit_duration = 10
experimental = true

[experimental_features]
leader = true
rpc_port = 8081
id = 1
nodes = []

[merge_policy]
kind = "log"
min_merge_size = 8
min_layer_size = 10_000
level_log_size = 0.75